# Time attribute in the dataset, using the ingestion column
TimeAttribute=ingestion

# Elevation attribute in the dataset
ElevationAttribute=elevation

# Schema definition, with the time field ingestion as a Date
Schema=*the_geom:Polygon,location:String,ingestion:String,elevation:Integer

# Property collectors to extract the time using timeregex
PropertyCollectors=TimestampFileNameExtractorSPI[timeregex](ingestion)